apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: RequestResponse
    resources:
    - group: ""
      resources: ["pods", "services"]
  - level: None
    resources:
    - group: ""
      resources: ["secrets"]
    namespaces: ["kube-system"]
  - level: Request
    resources:
    - group: "apps"
      resources: ["deployments"]
  - level: Metadata
---
  - --audit-policy-file=/etc/kubernetes/audit/policy.yaml
  - --audit-log-path=/var/log/kubernetes/audit/audit.log
  - --audit-log-maxage=14
  - --audit-log-maxbackup=5
volumeMounts:
- mountPath: /etc/kubernetes/audit
  name: audit
  readOnly: true
- mountPath: /var/log/kubernetes/audit
  name: audit-log
  readOnly: false

volumes:
- name: audit
  hostPath:
    path: /etc/kubernetes/audit
    type: DirectoryOrCreate
- name: audit-log
  hostPath:
    path: /var/log/kubernetes/audit
    type: DirectoryOrCreate
