apiVersion: v1
kind: Pod
metadata:
  labels:
  name: init-pod-nginx
spec:
  initContainers:
  - image: busybox
    name: init
    command: ["sh", "-c", "echo Test > /work-dir/index.html"]
    volumeMounts:
    - name: empty-vol
      mountPath: /work-dir
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: empty-vol
      mountPath: /usr/share/nginx/html
  volumes:
  - name: empty-vol
    emptyDir: {}
