apiVersion: batch/v1
kind: Job
metadata:
  name: busy
spec:
  completions: 5
  parallelism: 5
  activeDeadlineSeconds: 10
  template:
    metadata: {}
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - echo hello;sleep 30;echo world
        - -o
        - yaml
        image: busybox
        name: busy
        resources: {}
      restartPolicy: Never
status: {}
