apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi-pod
  name: multi-pod
spec:
  containers:
  - image: busybox
    name: busybox1
    command: ["sleep", "3600"]
  - image: busybox
    name: busybox2
    command: ["sleep", "3600"]
  restartPolicy: Never
