apiVersion: v1
kind: Pod
metadata:
  name: shared-data
spec:
  containers:
  - image: busybox
    name: writer
    command: ["sh", "-c", "echo Hello > /data/message; sleep 3600"]
    volumeMounts:
    - name: shared-vol
      mountPath: /data
  - image: busybox
    name: reader
    command: ["sh", "-c", "cat /data/message; sleep 3600"]
    volumeMounts:
    - name: shared-vol
      mountPath: /data
  volumes:
  - name: shared-vol
    emptyDir: {}
