apiVersion: v1
kind: Pod
metadata:
  name: logger
  namespace: default
spec:
  initContainers:
  - image: busybox
    name: shipper
    command: ["sh", "-c", "tail -f /var/log/app.log"]
    volumeMounts:
    - name: share-vol
      mountPath: /var/log
    restartPolicy: Always
  containers:
  - image: busybox
    name: app
    command: ["sh", "-c", "while true; do date >> /var/log/app.log; sleep 1; done"]
    volumeMounts:
    - name: share-vol
      mountPath: /var/log
  volumes:
  - name: share-vol
    emptyDir: {}
