apiVersion: v1
kind: Pod
metadata:
  name: db-pod
spec:
  containers:
  - image: postgres:13
    name: db-pod
    env:
    - name: APP_ENV
      value: production
    - name: DB_PORT
      value: "5432"
  volumes:
  - name: db-data
    persistentVolumeClaim:
      claimName: dbA


env:
- name: DB_PASSWORD
  valueFrom:
    secretKeyRef:
      name: db-secret
      key: DB_PASSWORD

envFrom:
- configMapRef:
    name: app-config



  volumeMounts:
  - name: config-vol
    mountPath: /etc/config
volumes:
- name: config-vol
  configMap:
    name: app-config

  volumeMounts:
  - name: secret-vol
    mountPath: /etc/secret
volumes:
- name: secret-vol
  secret:
    secretName: app-secret
