apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-cron
  namespace: dev
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: busybox
            name: cleaner
            command: ["sh", "-c", "echo cleanup"]
          restartPolicy: Never
