apiVersion: batch/v1
kind: CronJob
metadata:
  name: business-hours-check
spec:
  schedule: "*/10 08-17 * * 1-5"
  jobTemplate:
    spec:
      completions: 1
      template:
        spec:
          containers:
          - image: healthcheck:v1
            name: business-hours-check
            command: ["sh", "-c", "curl http://api.internal/health"]
          restartPolicy: Never
