apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-backup
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: backup:v1
            name: daily-backup
            command: ["./backup.sh"]
          restartPolicy: OnFailure
