apiVersion: batch/v1
kind: CronJob
metadata:
  name: hourly-cleanup
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      completions: 1
      template:
        spec:
          containers:
          - image: busybox
            name: hourly-cleanup
            command: ["sh", "-c", "rm -rf /tmp/*.log"]
          restartPolicy: Never
