apiVersion: v1
kind: Pod
metadata:
  labels:
  name: init-pod
spec:
  initContainers:
  - image: busybox
    name: wait-service
    command: ["sleep", "10"]
  containers:
  - image: nginx
    name: app
  - image: busybox
    name: sidecar
