apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-init-container
  namespace: mars
spec:
  replicas: 1
  selector:
    matchLabels:
      id: test-init-container
  template:
    metadata:
      labels:
        id: test-init-container
    spec:
      volumes:
      - name: web
        emptyDir: {}
      initContainers:
      - name: init-con
        image: busybox:1.31.0
        command: ["sh", "-c", "echo check this out! > /usr/share/nginx/html/index.html"]
        volumeMounts:
        - name: web
          mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: nginx:1.17.3-alpine
        volumeMounts:
        - name: web
          mountPath: /usr/share/nginx/html

