apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: dev
spec:
  containers:
  - image: nginx
    name: web
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
      periodSeconds: 10


    readinessProbe:
      httpGet:
        path: /ready
        port: 80
    periodSeconds: 5
    initialDelaySeconds: 3


