apiVersion: batch/v1
kind: Job
metadata:
  name: backup-job
  namespace: exam
  labels:
    id: backup
spec:
  completions: 5
  parallelism: 3
  template:
    spec:
      containers:
      - image: alpine
        name: exam
        command: ["echo", "backup"]
      restartPolicy: Never

