apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
  namespace: exam
spec:
  completions: 3
  parallelism: 2
  template:
    spec:
      containers:
      - image: busybox
        name: my-job
        command: ["echo", "done"]
      restartPolicy: Never


