apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db
  name: db
spec:
  serviceName: db-svc
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: postgres:15
        name: postgres
        volumeMounts:
        - name: set-vol
          mountPath: /var/lib/data
  volumeClaimTemplates:
  - metadata:
      name: set-vol
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
