apiVersion: batch/v1
kind: Job
metadata:
  name: batch-processor
spec:
  completions: 10
  parallelism: 3
  template:
    spec:
      containers:
      - image: python:3.9
        name: batch-processor
        command: ["python", "process.py"]
      restartPolicy: Never


