apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  template:
    spec:
      containers:
      - image: busybox
        name: batch-job
        command: ["echo", "Processing"]
      restartPolicy: Never
  parallelism: 3
  completions: 6
