apiVersion: batch/v1
kind: Job
metadata:
  name: init-job
  namespace: dev
  labels:
    app: init
    tier: jobs
spec:
  completions: 3
  parallelism: 3
  template:
    spec:
      containers:
      - image: alpine:3.17
        name: init-container
        command: ["echo", "init"]
      restartPolicy: Never
