apiVersion: batch/v1
kind: Job
metadata:
  name: video-encoder
spec:
  completions: 10
  parallelism: 2
  template:
    spec:
      containers:
      - image: ffmpeg:latest
        name: video-encoder
        command: ["sh", "-c", "ffmpeg -i input.mp4 -c:v libx264 output.mp4"]
      restartPolicy: OnFailure
