apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-dev
  namespace: development
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
