apiVersion: v1
kind: Pod
metadata:
  name: db-pod
spec:
  containers:
    - image: postgres:14
      name: db-pod
      env:
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: db-creds
            key: username
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-creds
            key: password

