apiVersion: v1
data:
  API_KEY: YWJjMTIzeHl6
  DB_PASSWORD: c3VwZXJzZWNyZXQ=
kind: Secret
metadata:
  creationTimestamp: "2026-02-03T19:32:06Z"
  name: web-creds
  namespace: sandbox
  resourceVersion: "34913712"
  uid: dcc1047c-32a3-4de8-9804-6440cd919e8d
type: Opaque
