apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  containers:
  - image: nginx
    name: web-pod
    volumeMounts:
    - name: secret-vol
      mountPath: /etc/nginx/ssl/
  volumes:
  - name: secret-vol
    secret:
      secretName: tls-secret
