apiVersion: v1
kind: Pod
metadata:
  labels:
    app: database
  name: db
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: secret
    image: mysql
    name: db
    ports:
    - containerPort: 3306
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
