apiVersion: v1
kind: Pod
metadata:
  labels:
    tier: monitoring
  name: monitor
spec:
  containers:
  - env:
    - name: LOG_LEVEL
      value: debug
    image: busybox
    name: monitor
    ports:
    - containerPort: 9090
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
