apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
  - image: nginx
    name: pvc-pod
    volumeMounts:
    - name: data-vol
      mountPath: /data
  volumes:
  - name: data-vol
    persistentVolumeClaim:
      claimName: pvc-data
