apiVersion: v1
kind: Pod
metadata:
  name: data-pod
spec:
  containers:
  - image: nginx
    name:  data-pod
    volumeMounts:
    - name: app-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: app-storage
    persistentVolumeClaim:
      claimName: app-storage

