apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx:alpine
    name: nginx
    volumeMounts:
    - name: local-pvc
      mountPath: /var/www/html
  volumes:
  - name: local-pvc
    persistentVolumeClaim:
      claimName: local-pvc

