apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: silver-storage
provisioner: docker.io/hostpath
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: PersistentVolumeClaim
metadata:
  name: silver-pvc
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: silver-storage


