apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  containers:
  - image: nginx
    name: web-pod
    volumeMounts:
    - name: web-vol
      mountPath: /usr/share/nginx/html
  volumes:
  - name: web-vol
    persistentVolumeClaim:
      claimName: web-pvc
