apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitor-ds
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - name: monitor-container
        image: busybox
        command: ["sleep", "3600"]
