apiVersion: v1
kind: Pod
metadata:
  name:  pod-cm
spec:
  containers:
  - image: nginx
    name: pod-cm
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password





    volumeMounts:
    - name: config-map
      mountPath: /etc/config
  volumes:
  - name: config-map
    configMap:
      name: app-config

