apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-blue
  namespace: team-blue
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-blue
  namespace: team-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-blue
  template:
    metadata:
      labels:
        app: deploy-blue
    spec:
      serviceAccountName: sa-blue
      containers:
      - name: app
        image: nginx
        volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: token
          readOnly: true
      volumes:
      - name: token
        projected:
          sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 7200

