apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
  namespace: exam
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: busybox
            name: my-cronjob
            command: ["echo", "hello"]
          restartPolicy: Never

