apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: blue-new
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: blue
  template:
    metadata:
      labels:
        app: myapp
        version: blue
    spec:
      containers:
      - image: nginx
        name: nginx
