apiVersion: v1
kind: Pod
metadata:
  name: tolerant-pod
spec:
  containers:
  - image: nginx
    name: tolerant-pod
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-name.kubernetes.io
            operator: In
            values:
            - node01
  tolerations:
  - key: IT
    operator: Equals
    value: Kiddie
    effect: NoSchedule
