apiVersion: v1
kind: Pod
metadata:
  labels:
    run: watcher
  name: watcher
spec:
  containers:
  - image: nginx
    name: watcher
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
