apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  fsType: ext4
  type: gp3
reclaimPolicy: Retain
volumeBindingMode: WaitforFirstConsumele
allowVolumeExpansion: true
