apiVersion: v1
kind: Pod
metadata:
  name: git-clone-pod
  namespace: default
spec:
  initContainers:
  - image: alpine/git:latest
    name: clone-repo
    command: ["sh", "-c", "cd /repo && git clone https://github.com/kubernetes/website.git ."]
    volumeMounts:
    - name: git-volume
      mountPath: /repo
  containers:
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: git-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: git-volume
    emptyDir: {}
