apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    envFrom:
    - configMapRef:
        name: app-config
    - secretRef:
        name: api-secret

