apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-canary
  name: app-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      track: canary
  strategy: {}
  template:
    metadata:
      labels:
        app: myapp
        track: canary
    spec:
      containers:
      - image: nginx:1.22
        name: nginx
        resources: {}
status: {}
