apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-stable
  name: app-stable
spec:
  replicas: 9
  selector:
    matchLabels:
      app: myapp
      track: stable
  strategy: {}
  template:
    metadata:
      labels:
        app: myapp
        track: stable
    spec:
      containers:
      - image: nginx:1.21
        name: nginx
        resources: {}
status: {}
