apiVersion: v1
kind: Pod
metadata:
  name: cache-pod
spec:
  containers:
  - image: nginx
    name: web
  - image: busybox
    name: cache
    command: ["sleep", "3600"]
    volumeMounts:
    - name: cache-vol
      mountPath: /cache
  volumes:
  - name: cache-vol
    emptyDir: {}
