apiVersion: v1
kind: Pod
metadata:
  name: logger-pod
spec:
  containers:
  - image: busybox
    name: logger-pod
    command: ["sleep","3600"]
    volumeMounts:
    - name: log-vol
      mountPath: /host-logs
  volumes:
  - name: log-vol
    hostPath:
      path: /var/log
      type: Directory
