apiVersion: batch/v1
kind: Job
metadata:
  name: data-job
  namespace: batch
spec:
  activeDeadlineSeconds: 60
  template:
    spec:
      containers:
      - image: busybox
        name: busybox
        command: ['sh', '-c', 'echo "processing complete"']
      restartPolicy: Never

