apiVersion: batch/v1
kind: Job
metadata:
  name: backup
spec:
  completions: 3
  parallelism: 2
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: backup:v1
        name: backup
        command: ["./backup.sh"]

