apiVersion: v1
kind: Pod
metadata:
  name: logger
spec:
  terminationGracePeriodSeconds: 20
  containers:
  - name: logger
    image: nginx
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo started > /tmp/start.txt"]
      preStop:
        exec:
          command: ["/bin/sh","-c","sleep 5"]
