apiVersion: v1
kind: Pod
metadata:
  name: time-pod
spec:
  containers:
  - image: busybox
    name: time-pod
    command: ["tail", "-f", "/dev/null"]
    securityContext:
      capabilities:
        drop:
          - ALL
        add:
          - SYS_TIME
          - CHOWN
