apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-shell
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 2000
  containers:
  - image: ubuntu
    name: ubuntu-shell
    command: ["sh", "-c", "while true; do echo hello; sleep 10; done"]
    securityContext:
      capabilities:
        drop:
          - ALL
        add:
          - CHOWN
      allowPrivilegeEscalation: false

