apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  securityContext:
    fsGroup: 4000
  containers:
  - image: busybox
    name: volume-pod
    command: ["sleep","3600"]
    volumeMounts:
    - name: data-vol
      mountPath: /data
  volumes:
  - name: data-vol
    emptyDir: {}
