apiVersion: v1
kind: Pod
metadata:
  name: readonly-pod
spec:
  containers:
  - image: busybox
    name: readonly-pod
    securityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
    command: ["sleep", "3600"]
