apiVersion: v1
kind: Pod
metadata:
  name: python-app
spec:
  containers:
  - image: python
    name: python-app
    command: ["python", "-m", "http.server", "8000"]
    securityContext:
      capabilities:
        drop:
          - ALL
        add:
          - NET_BIND_SERVICE
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true

