apiVersion: v1
kind: Pod
metadata:
  name: web-secure
spec:
  containers:
  - image: nginx
    name: web-secure
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    volumeMounts:
    - name: cache-vol
      mountPath: /cache
  volumes:
  - name: cache-vol
    emptyDir: {}

