apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 3000
  containers:
  - image: busybox
    name: multi-pod
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 2000

