apiVersion: v1
kind: Pod
metadata:
  name: limited-pod
spec:
  containers:
  - image: redis:alpine
    name: limited-pod
    resources:
      requests:
        cpu: 0.5
        memory: 128Mi
      limits:
        cpu: 1
        memory: 256Mi
