apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
spec:
  containers:
  - image: busybox
    name: main
    command: ["sleep", "3600"]
    livenessProbe:
      exec:
        command:
        - ls
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 10


apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod
spec:
  containers:
  - image: busybox
    name: main
    command: ["sleep", "3600"]
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10


apiVersion: v1
kind: Pod
metadata:
  name: startup-pod
spec:
  containers:
  - image: busybox
    name: main
    command: ["sleep", "3600"]
    startupProbe:
      tcpSocket:
        port: 3306
      failureThreshold: 30
      periodSeconds: 10
