apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  containers:
  - image: nginx
    name: secure-pod
    securityContext:
      runAsNonRoot: true
  securityContext:
    runAsUser: 1000
    fsGroup: 2000

