apiVersion: v1
kind: Pod
metadata:
  name: vol-pod
spec:
  containers:
    - image: nginx
      name: vol-pod
      volumeMounts:
        - mountPath: /etc/config
          name: app-config
  volumes:
    - name: app-config
      configMap:
        name: app-config
