apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp-green
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webapp
      version: v2
  strategy: {}
  template:
    metadata:
      labels:
        app: webapp
        version: v2
    spec:
      containers:
      - image: nginx:1.22
        name: webapp
        resources: {}
status: {}
