apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp-prod
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webapp
      version: v1
  strategy: {}
  template:
    metadata:
      labels:
        app: webapp
        version: v1
    spec:
      containers:
      - image: nginx:1.21
        name: webapp-prod
        resources: {}
status: {}
